### PR TITLE
adding message files for CB

### PR DESCRIPTION
**Pull request by annaxuphoto**
# Description
Checking in `django.po` and `django.mo` message files for Curriculum Builder UI translated elements

## Links

- [spec]()
- [jira]()

## Testing story

# Reviewer Checklist:

- [ ] Tests provide adequate coverage
- [ ] Code is well-commented
- [ ] New features are translatable or updates will not break translations
- [ ] Relevant documentation has been added or updated
- [ ] User impact is well-understood and desirable
- [ ] Pull Request is labeled appropriately
- [ ] Follow-up work items (including potential tech debt) are tracked and linked

### CODE REVIEW

**Review by bethanyaconnor — APPROVED** [review]
Do you actually need to check in the .po files? I could see reasons to still check them in, just curious

**Comment by annaxuphoto** [comment]
We don't need it, but I'd like to have them for human-readability

**Comment by bethanyaconnor** [comment]
Makes sense!

**Comment by Hamms** [comment]
I will reiterate that I do not think we should be storing serialized data files in git

**Pull request merged**
