### PR TITLE
Filter unit & curriculum fieldsets

### PR DESCRIPTION
**Pull request by davidsbailey**
# Description

## Links

- [spec]()
- [jira]()

## Testing story

# Reviewer Checklist:

- [ ] Tests provide adequate coverage
- [ ] Code is well-commented
- [ ] New features are translatable or updates will not break translations
- [ ] Relevant documentation has been added or updated
- [ ] User impact is well-understood and desirable
- [ ] Pull Request is labeled appropriately
- [ ] Follow-up work items (including potential tech debt) are tracked and linked

### CODE REVIEW

**Comment by davidsbailey** [comment]
Hey @dmcavoy , would you be interested in taking this just-started PR and running with it to customize the Unit admin page for partners to hide the fields they shouldn't see? I split out the hidden-field requests in the [bug bash doc](https://docs.google.com/document/d/1pVJ5vigQPyUEzPg2IgIB9on3rgej2meTHn1eJhQhHUk/edit#). I'm not sure what your other priorities are so no worries if you have other stuff you need to finish.

**Comment by dmcavoy** [comment]
@davidsbailey - I filtered it down. Will add a screenshot in a minute

**Comment by dmcavoy** [comment]
# Before

Screen Shot 2019-10-31 at 12 33 05 PM
Screen Shot 2019-10-31 at 12 33 14 PM

# After

Screen Shot 2019-10-31 at 12 32 45 PM
Screen Shot 2019-10-31 at 12 32 52 PM

**Comment by dmcavoy** [comment]
Curriculum Edit Page 

# Before

Screen Shot 2019-10-31 at 1 06 36 PM
Screen Shot 2019-10-31 at 1 06 56 PM
Screen Shot 2019-10-31 at 1 06 45 PM


# After

Screen Shot 2019-10-31 at 1 05 51 PM
Screen Shot 2019-10-31 at 1 05 43 PM

**Comment by davidsbailey** [comment]
LGTM!

**Pull request merged**
